### ISSUE TITLE
Feature Request Workflow -- Copy text Caption files from dataset to subfolder with Subset

### ISSUE THREAD

**Issue by rafstahelin** [daxcay/ComfyUI-DataSet#4]
Request for workflow to automate the matching of SD training Captions in diffirent folders

The Workflow scans a parent folder repositary of the complete dataset of images and captions with same filenames. 
It then scans subfolder with the main path, and analyses the filenames of the subset of images. 
Lastly, the workflow will then copy over the matching caption files from parent folder to the subset folder.

As a result the subset folder will contain all the caption txt files that match the names of images in subfolder. 

This is extremely useful in training with edited datasets. Sometimes datasets have hundreds, or thousands of paired image-captions. This workflow removes the need to find captions one by one with a human worker. DRMN together with JCDN are perfect tools to succeed at speeding up preparing datasets

**Comment by akr1999** [comment]
Will make a small node for it.

**Comment by daxcay** [comment]
https://github.com/daxcay/ComfyUI-DRMN/commit/1408357d1e2615343cf9273717179a73d4b7659f

the required node !
