### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by sneccc** [daxcay/ComfyUI-DataSet#5]
Getting this error on big datasets
![image](https://github.com/daxcay/ComfyUI-DataSet/assets/61990796/6d8d019a-db59-4e7a-a333-65ae711d43a8)

**Comment by daxcay** [comment]
Please update the new version is fixed

**Comment by daxcay** [comment]
https://github.com/daxcay/ComfyUI-DataSet/commit/748d3eaa96305c8aded8631352fcd3274a9e3dd2

Fixed the issue with encoding
