### ISSUE TITLE
Feature Request: trigger words to files

### ISSUE THREAD

**Issue by rafstahelin** [daxcay/ComfyUI-DataSet#6]
request for Dataset: a node to save each concept which are a mix of letters and numbers into a file. Useful to know what specific concepts have been trained in a model. Usually people use a name in real world but mixed with number to override previous knowledge.
Input: dataset file path with multiple caption files (txt)
Output: one file per found trigger word plus surrounding words within the comma phrase. Files saved to a designated folder 

Example: tr1ggerw0rd style outfit, high quality, masterpiece
Output: file containing "tr1ggerw0rd style outfit"

**Comment by daxcay** [comment]
Ok,

**Comment by daxcay** [comment]
Please update node
