### ISSUE TITLE
Save Image Pro issue.

### ISSUE THREAD

**Issue by DarkAlchy** [daxcay/ComfyUI-DataSet#8]
My workflows (Linux and Windows) use this node and I had to go back to use it today to see it in red.  I looked, uninstalled to reinstall and the same thing.  I then double-clicked and can load the normal (non pro), but the pro version refuses as it just never appears (and if already in a WF it is in red).

**Comment by daxcay** [comment]
Hi, please attach some screen shot here so i can understand it.

[Edit]

I checked it my self please wait i am on it.

**Comment by daxcay** [comment]
Hi, i fixed it, please update and confirm it, also please change names widget to input before connecting.

**Comment by DarkAlchy** [comment]
I deleted the node and git cloned it.  It works, so thank you.
